spring.application.name=trackly-api
spring.datasource.url=jdbc:postgresql://localhost:5432/trackly
spring.datasource.username=trackly_app
spring.datasource.password=${TRACKLY_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
